version: "3.8"
services:
  ml:
    build:
      context: .
      dockerfile: ./Dockerfile.jammy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ "0" ]
              capabilities: [ gpu ]
    volumes:
      - ../:/workspaces:cached
      - ../data/:/workspaces/data:cached
    ports:
      - "5000:5000"
    command: sleep infinity
