version: '3.8'

services:
  ml:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - devcontainercli-true
    volumes:
      - ..:/workspace:cached
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    command: /bin/sh -c "while sleep 1000; do :; done"
