name: 'build and push to registry' 
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PACKAGE_NAME: machine-learning

jobs:
  build:
    name: build-image-and-push
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.actor }}/${{ env.PACKAGE_NAME }}
          cacheFrom: ghcr.io/${{ github.actor }}/${{ env.PACKAGE_NAME }}
          push: always
      # - name: Install latest devcontainer cli
      #   run: npm install -g @devcontainers/cli

      # - name: Build devcontainer
      #   run: |
      #     devcontainer build ./src/machine-learning --workspace-folder ./src/machine-learning --image-name ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.PACKAGE_NAME }}
      #     docker tag ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.PACKAGE_NAME }} ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.PACKAGE_NAME }}:latest

      # - name: Push container
      #   run:  docker push ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.PACKAGE_NAME }}:latest
